package web.model;

// IComponentInstanceGson.java

//Generated by https://quicktype.io

import java.util.Map;

public class IComponentInstanceGson {
	private Component component;
	private Map<String, String> parameterValues;
	private Annotations satisfactionOfRequiredInterfaces;
	private Annotations annotations;

	public Component getComponent() { return component; }
	public void setComponent(Component value) { this.component = value; }

	public Map<String, String> getParameterValues() { return parameterValues; }
	public void setParameterValues(Map<String, String> value) { this.parameterValues = value; }

	public Annotations getSatisfactionOfRequiredInterfaces() { return satisfactionOfRequiredInterfaces; }
	public void setSatisfactionOfRequiredInterfaces(Annotations value) { this.satisfactionOfRequiredInterfaces = value; }

	public Annotations getAnnotations() { return annotations; }
	public void setAnnotations(Annotations value) { this.annotations = value; }
}

